google-cloud-sdk:
  image: openbridge/google-cloud
  volumes:
    - ./cron/crontab.conf:/crontab.conf
    - ./auth/prod.json:/auth.json
  container_name: google-cloud-sdk
  env_file:
    - ./env/prod.env
  restart: always
  command: cron
  tty: true
  ulimits:
    nproc: 65535
    nofile:
        soft: 49999
        hard: 99999
